import "server-only";
import { randomBytes } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

/**
 * Image storage.
 *
 * Photos are the single heaviest thing this site serves — 20 phone photos per
 * car, and most buyers are on a mid-range Android over 4G. Two decisions
 * follow from that:
 *
 *   1. Store a KEY, never a URL. `listing_images.storage_key` holds an opaque
 *      key so moving CDN later is a config change, not a data migration over
 *      millions of rows.
 *   2. Never serve the original. A 4MB 4000x3000 phone JPEG resized on the fly
 *      to 480px is the difference between a search page that loads and one
 *      that doesn't.
 *
 * `local` writes to public/uploads and is fine for development. It is not
 * fine for production — you will run out of disk and have no CDN in front.
 */

export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024;
const MAX_IMAGE_PIXELS = 40_000_000;

/**
 * Where the `local` provider writes.
 *
 * Deliberately NOT bare `process.cwd()`. The server's working directory is
 * not guaranteed to be the project root — a systemd unit with a different
 * WorkingDirectory, pm2, a monorepo task runner, or `next dev <dir>` launched
 * from elsewhere all change it. When that happens uploads land outside
 * public/, every image 404s, and nothing errors: the upload returns 200 and
 * the file is simply written into the void.
 *
 * Set UPLOAD_DIR to an absolute path to pin it.
 */
function localUploadDir(): string {
  return (
    process.env.UPLOAD_DIR ?? path.join(process.cwd(), "public", "uploads")
  );
}

export const ACCEPTED_TYPES = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/avif",
  "image/heic",
  "image/heif",
]);

export interface StoredImage {
  key: string;
  bytes: number;
}

const STORAGE_KEY = /^\d{6}\/[a-f0-9]{32}\.(?:jpg|png|webp|avif|heic)$/;

function newKey(ext: string): string {
  const now = new Date();
  const yyyymm = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}`;
  return `${yyyymm}/${randomBytes(16).toString("hex")}.${ext}`;
}

export async function storeImage(
  file: File,
): Promise<{ ok: true; image: StoredImage } | { ok: false; error: string }> {
  if (!ACCEPTED_TYPES.has(file.type)) {
    return { ok: false, error: "That file type isn't supported." };
  }
  if (file.size > MAX_UPLOAD_BYTES) {
    return { ok: false, error: "Images must be under 10 MB." };
  }

  const original = Buffer.from(await file.arrayBuffer());

  /**
   * Content-Type and file extensions are attacker-controlled. Fully decode
   * and re-encode the image instead of trusting magic bytes: this rejects
   * malformed files, strips metadata/trailing payloads and ensures an SVG or
   * executable can never be stored under an image extension.
   */
  let buffer: Buffer;
  try {
    buffer = await sharp(original, { limitInputPixels: MAX_IMAGE_PIXELS })
      .rotate()
      .resize({
        width: 2400,
        height: 2400,
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: 84, effort: 4 })
      .toBuffer();
  } catch {
    return { ok: false, error: "That file isn't a valid image." };
  }

  const key = newKey("webp");
  const provider = process.env.IMAGE_PROVIDER ?? "local";

  if (provider === "cloudflare") {
    return storeOnCloudflare(key, buffer, "image/webp");
  }

  const dest = path.join(localUploadDir(), key);
  await mkdir(path.dirname(dest), { recursive: true });
  await writeFile(dest, buffer);

  return { ok: true, image: { key, bytes: buffer.length } };
}

/** Remove only keys generated by this module; caller input never becomes a path. */
export async function removeStoredImage(key: string): Promise<boolean> {
  if (!STORAGE_KEY.test(key)) return false;
  const provider = process.env.IMAGE_PROVIDER ?? "local";
  if (provider === "cloudflare") return removeFromCloudflare(key);

  const root = path.resolve(localUploadDir());
  const target = path.resolve(root, key);
  if (!target.startsWith(`${root}${path.sep}`)) return false;
  try {
    await unlink(target);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return true;
    console.error("Local image cleanup failed", error);
    return false;
  }
}

async function storeOnCloudflare(
  key: string,
  buffer: Buffer,
  mime: string,
): Promise<{ ok: true; image: StoredImage } | { ok: false; error: string }> {
  const account = process.env.CF_IMAGES_ACCOUNT_ID;
  const token = process.env.CF_IMAGES_API_TOKEN;
  if (!account || !token) {
    return { ok: false, error: "Image storage is not configured." };
  }

  const form = new FormData();
  form.append("file", new Blob([new Uint8Array(buffer)], { type: mime }), key);
  form.append("id", key);

  const res = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${account}/images/v1`,
    { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form },
  );

  if (!res.ok) {
    console.error(`Cloudflare Images upload failed: ${res.status}`);
    return { ok: false, error: "Upload failed. Try again." };
  }

  return { ok: true, image: { key, bytes: buffer.length } };
}

async function removeFromCloudflare(key: string): Promise<boolean> {
  const account = process.env.CF_IMAGES_ACCOUNT_ID;
  const token = process.env.CF_IMAGES_API_TOKEN;
  if (!account || !token) return false;
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${account}/images/v1/${encodeURIComponent(key)}`,
    { method: "DELETE", headers: { Authorization: `Bearer ${token}` } },
  );
  if (!response.ok && response.status !== 404) {
    console.error(`Cloudflare Images cleanup failed: ${response.status}`);
    return false;
  }
  return true;
}
