import "server-only";
import { randomBytes } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { CLOUDFLARE_KEY, UPLOAD_KEY } from "./keys";
import { privateCloudflareUrl, readPrivateCloudflareImage } from "./cloudflare";
import { logSafeError } from "@/lib/operations/safe-error";

/**
 * Image storage.
 *
 * Photos are the single heaviest thing this site serves — 20 phone photos per
 * car, and most buyers are on a mid-range Android over 4G. Two decisions
 * follow from that:
 *
 *   1. Store a KEY, never a URL. `listing_images.storage_key` holds an opaque
 *      key so moving CDN later is a config change, not a data migration over
 *      millions of rows.
 *   2. Never serve the original. A 4MB 4000x3000 phone JPEG resized on the fly
 *      to 480px is the difference between a search page that loads and one
 *      that doesn't.
 *
 * `local` writes outside public/ and is fine for development. It is not
 * fine for production — you will run out of disk and have no CDN in front.
 */

export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024;
const MAX_IMAGE_PIXELS = 40_000_000;

function imageProvider(): "local" | "cloudflare" {
  const provider = process.env.IMAGE_PROVIDER ?? "local";
  if (provider !== "local" && provider !== "cloudflare") {
    throw new Error(`Unsupported IMAGE_PROVIDER: ${provider}`);
  }
  return provider;
}

/**
 * Where the `local` provider writes.
 *
 * Deliberately NOT bare `process.cwd()`. The server's working directory is
 * not guaranteed to be the project root — a systemd unit with a different
 * WorkingDirectory, pm2, a monorepo task runner, or `next dev <dir>` launched
 * from elsewhere all change it. An absolute path keeps reads, uploads and
 * cleanup pointed at the same private storage directory.
 *
 * Set UPLOAD_DIR to an absolute path to pin it.
 */
function localUploadDir(): string {
  const root = path.resolve(process.env.UPLOAD_DIR || path.join(process.cwd(), ".uploads"));
  const publicRoot = path.resolve(process.cwd(), "public");
  const relative = path.relative(publicRoot, root);
  if (!relative || (!relative.startsWith(`..${path.sep}`) && relative !== ".." && !path.isAbsolute(relative))) {
    throw new Error("UPLOAD_DIR must be outside public/ so image access cannot bypass authorization.");
  }
  return root;
}

export const ACCEPTED_TYPES = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/avif",
  "image/heic",
  "image/heif",
]);

export interface StoredImage {
  key: string;
  bytes: number;
}

// Preserve the original development fixture keys when moving storage out of public/.
const STORAGE_KEY = /^(?:\d{6}\/[a-f0-9]{32}\.(?:jpg|png|webp|avif|heic)|listings\/[a-z0-9-]+\.jpg)$/;

export function isStoredImageKey(key: string): boolean {
  return STORAGE_KEY.test(key) || UPLOAD_KEY.test(key);
}

function newKey(ext: string): string {
  const now = new Date();
  const yyyymm = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}`;
  return `${yyyymm}/${randomBytes(16).toString("hex")}.${ext}`;
}

export async function storeImage(
  file: File,
): Promise<{ ok: true; image: StoredImage } | { ok: false; error: string }> {
  if (!ACCEPTED_TYPES.has(file.type)) {
    return { ok: false, error: "That file type isn't supported." };
  }
  if (file.size > MAX_UPLOAD_BYTES) {
    return { ok: false, error: "Images must be under 10 MB." };
  }

  const original = Buffer.from(await file.arrayBuffer());

  /**
   * Content-Type and file extensions are attacker-controlled. Fully decode
   * and re-encode the image instead of trusting magic bytes: this rejects
   * malformed files, strips metadata/trailing payloads and ensures an SVG or
   * executable can never be stored under an image extension.
   */
  let buffer: Buffer;
  try {
    buffer = await sharp(original, { limitInputPixels: MAX_IMAGE_PIXELS })
      .rotate()
      .resize({
        width: 2400,
        height: 2400,
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: 84, effort: 4 })
      .toBuffer();
  } catch {
    return { ok: false, error: "That file isn't a valid image." };
  }

  const key = newKey("webp");
  const provider = imageProvider();

  if (provider === "cloudflare") {
    return storeOnCloudflare(key, buffer, "image/webp");
  }

  const dest = path.join(localUploadDir(), key);
  await mkdir(path.dirname(dest), { recursive: true });
  await writeFile(dest, buffer);

  return { ok: true, image: { key, bytes: buffer.length } };
}

/** Remove only keys generated by this module; caller input never becomes a path. */
export async function removeStoredImage(key: string): Promise<boolean> {
  if (!isStoredImageKey(key)) return false;
  const provider = imageProvider();
  if (provider === "cloudflare") return removeFromCloudflare(key);
  if (CLOUDFLARE_KEY.test(key)) return false;

  const root = path.resolve(localUploadDir());
  const target = path.resolve(root, key);
  if (!target.startsWith(`${root}${path.sep}`)) return false;
  try {
    await unlink(target);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return true;
    logSafeError("image.local_cleanup_failed", error);
    return false;
  }
}

/** Local uploads can be written after Next's public-file manifest is built. */
export async function readLocalStoredImage(key: string): Promise<Buffer | null> {
  if (!STORAGE_KEY.test(key) || key.includes("\\")) return null;
  const root = path.resolve(localUploadDir());
  const target = path.resolve(root, key);
  if (!target.startsWith(`${root}${path.sep}`)) return null;
  try {
    const buffer = await readFile(target);
    return key.endsWith(".webp") ? buffer : await sharp(buffer, { limitInputPixels: MAX_IMAGE_PIXELS })
      .rotate().resize({ width: 2400, height: 2400, fit: "inside", withoutEnlargement: true })
      .webp({ quality: 84 }).toBuffer();
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

async function storeOnCloudflare(
  key: string,
  buffer: Buffer,
  mime: string,
): Promise<{ ok: true; image: StoredImage } | { ok: false; error: string }> {
  const account = process.env.CF_IMAGES_ACCOUNT_ID;
  const token = process.env.CF_IMAGES_API_TOKEN;
  if (!account || !token) {
    return { ok: false, error: "Image storage is not configured." };
  }

  // Cloudflare custom IDs cannot be private. Validate delivery configuration
  // before creating an object, then persist the provider-issued UUID.
  try { privateCloudflareUrl("cf/00000000-0000-0000-0000-000000000000"); }
  catch { return { ok: false, error: "Private image storage is not configured." }; }

  const form = new FormData();
  form.append("file", new Blob([new Uint8Array(buffer)], { type: mime }), key);
  form.append("requireSignedURLs", "true");

  const res = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${account}/images/v1`,
    { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form, signal: AbortSignal.timeout(30_000) },
  );

  if (!res.ok) {
    console.error(`Cloudflare Images upload failed: ${res.status}`);
    return { ok: false, error: "Upload failed. Try again." };
  }

  const payload = await res.json() as { success?: boolean; result?: { id?: string; requireSignedURLs?: boolean } };
  const storedKey = `cf/${payload.result?.id ?? ""}`;
  if (!payload.success || !CLOUDFLARE_KEY.test(storedKey) || payload.result?.requireSignedURLs !== true) {
    if (CLOUDFLARE_KEY.test(storedKey)) await removeFromCloudflare(storedKey);
    return { ok: false, error: "Private image upload could not be verified." };
  }
  return { ok: true, image: { key: storedKey, bytes: buffer.length } };
}

async function removeFromCloudflare(key: string): Promise<boolean> {
  const account = process.env.CF_IMAGES_ACCOUNT_ID;
  const token = process.env.CF_IMAGES_API_TOKEN;
  if (!account || !token) return false;
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${account}/images/v1/${encodeURIComponent(CLOUDFLARE_KEY.exec(key)?.[1] ?? key)}`,
    { method: "DELETE", headers: { Authorization: `Bearer ${token}` }, signal: AbortSignal.timeout(15_000) },
  );
  if (!response.ok && response.status !== 404) {
    console.error(`Cloudflare Images cleanup failed: ${response.status}`);
    return false;
  }
  return true;
}

export async function readStoredImage(key: string): Promise<Buffer | null> {
  if (imageProvider() === "local") return readLocalStoredImage(key);
  // Legacy public custom IDs must be migrated before they can be served safely.
  if (!CLOUDFLARE_KEY.test(key)) return null;
  const buffer = await readPrivateCloudflareImage(key);
  return buffer ? sharp(buffer, { limitInputPixels: MAX_IMAGE_PIXELS }).rotate()
    .resize({ width: 2400, height: 2400, fit: "inside", withoutEnlargement: true })
    .webp({ quality: 84 }).toBuffer() : null;
}
