import type { Metadata } from "next";
import { ContentList, ContentPage, ContentSection, InlineLink } from "@/components/ContentPage";
import { abs } from "@/lib/seo/jsonld";

export const metadata: Metadata = { title: "Privacy Policy | JaniWheels", description: "How JaniWheels handles account, listing, contact and marketplace activity information.", alternates: { canonical: abs("/privacy") } };
const updated = "4 October 2026";

export default function PrivacyPage() { return <ContentPage eyebrow="Legal" title="Privacy Policy" intro="This policy describes the information JaniWheels uses to operate accounts, classifieds and marketplace safety features." updated={updated}>
  <ContentSection title="Information we handle"><ContentList><li>Account details such as name, email, optional phone number and authentication identifiers.</li><li>Listing, dealer, inspection and Sell My Car Assistance information you submit.</li><li>Images and public profile information selected for publication.</li><li>Session, security, reporting, moderation and basic marketplace activity records.</li><li>Messages or details you provide when requesting support.</li></ContentList></ContentSection>
  <ContentSection title="How information is used"><p>We use information to authenticate users, publish and manage listings, provide search and buyer tools, respond to service requests, prevent abuse, moderate content, maintain audit history and improve service reliability.</p></ContentSection>
  <ContentSection title="Public information"><p>Active listings and dealer or seller profiles may display the information needed for buyers to understand an advert and contact its seller. Do not include sensitive documents or unnecessary personal information in public text or images.</p></ContentSection>
  <ContentSection title="Google authentication"><p>When you choose Google sign-in, JaniWheels validates Google-provided identity information including a provider-specific account identifier, verified email, name and profile image where available. Google credentials and passwords are not stored by JaniWheels.</p></ContentSection>
  <ContentSection title="Sharing and service providers"><p>Information may be processed by infrastructure, email, image-storage, security and monitoring providers needed to operate JaniWheels. We may also disclose information where legally required or reasonably necessary to protect users and the service. We do not sell personal information as a standalone product.</p></ContentSection>
  <ContentSection title="Retention and choices"><ContentList>
    <li>Closing your account immediately hides your public profile and ads, stops alerts and revokes existing sign-ins. You can sign in within 30 days to restore the account. After this recovery period, personal profile and linked personal information is deleted or anonymized, except necessary complaint or dispute evidence.</li>
    <li>Sold, expired or deleted ads and images are retained with restricted access for up to 12 months after becoming inactive. Account closure or an approved earlier-deletion request can shorten this period.</li>
    <li>Inspection and Sell My Car Assistance personal details and messages are removed 12 months after completion or cancellation, or earlier under account closure.</li>
    <li>Resolved reports and necessary moderation evidence are retained for 24 months after resolution. Active complaints or documented legal requirements can place a hold on relevant evidence; holds are reviewed every 90 days.</li>
    <li>Detailed contact activity is retained for 90 days before removal and anonymous monthly aggregation. Alert recipient details and message bodies are removed 90 days after delivery or suppression; a minimal technical match record remains while the saved search exists to prevent duplicate alerts.</li>
    <li>Backups use a rolling 30-day window. Deleted data can remain in old backups until expiry. Restoration must reapply deletion records before public access resumes. Provider copies are handled according to available deletion and retention controls.</li>
  </ContentList><p>You may edit supported fields in your dashboard, close your account from <InlineLink href="/dashboard/profile">account settings</InlineLink>, or <InlineLink href="/contact">contact us</InlineLink> about an earlier-deletion request. Inactive accounts are not automatically deleted solely because you stop signing in.</p></ContentSection>
  <ContentSection title="Security and updates"><p>We use access controls, hashed credentials and secure session practices, but no internet service can promise absolute security. We may update this policy as JaniWheels and its providers change.</p></ContentSection>
</ContentPage>; }
