import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { desc, eq } from "drizzle-orm";
import { db } from "@/db";
import { cities } from "@/db/schema/geo";
import { makes, models } from "@/db/schema/taxonomy";
import { sellAssistanceEvents, sellAssistanceRequests } from "@/db/schema/trust";
import { users } from "@/db/schema/users";
import { getCurrentUser } from "@/lib/auth/session";
import { displayPkPhone, formatPkr, relativeTime } from "@/lib/format";
import { isSellAssistanceStatus, sellAssistanceStatusLabel } from "@/lib/trust/sell-assistance-policy";
import { SellAssistanceAdminForm } from "./SellAssistanceAdminForm";

export const metadata: Metadata = { title: "Sell My Car Assistance | Admin", robots: { index: false, follow: false } };
export default async function AdminSellAssistancePage() {
  const admin = await getCurrentUser(); if (!admin) redirect("/login?next=/admin/sell-assistance"); if (!admin.isAdmin) redirect("/");
  const [requests, events] = await Promise.all([
    db.select({ id: sellAssistanceRequests.id, status: sellAssistanceRequests.status, year: sellAssistanceRequests.year, mileageKm: sellAssistanceRequests.mileageKm, registrationCity: sellAssistanceRequests.registrationCity, ownershipStatus: sellAssistanceRequests.ownershipStatus, vehicleCondition: sellAssistanceRequests.vehicleCondition, expectedPricePkr: sellAssistanceRequests.expectedPricePkr, sellingTimeline: sellAssistanceRequests.sellingTimeline, address: sellAssistanceRequests.address, contactPhone: sellAssistanceRequests.contactPhone, preferredContact: sellAssistanceRequests.preferredContact, bestContactTime: sellAssistanceRequests.bestContactTime, sellerNotes: sellAssistanceRequests.sellerNotes, createdAt: sellAssistanceRequests.createdAt, updatedAt: sellAssistanceRequests.updatedAt, cityName: cities.name, makeName: makes.name, modelName: models.name, customerName: users.name, customerEmail: users.email })
      .from(sellAssistanceRequests).innerJoin(cities, eq(sellAssistanceRequests.cityId, cities.id)).innerJoin(makes, eq(sellAssistanceRequests.makeId, makes.id)).innerJoin(models, eq(sellAssistanceRequests.modelId, models.id)).innerJoin(users, eq(sellAssistanceRequests.requestedByUserId, users.id)).orderBy(desc(sellAssistanceRequests.updatedAt)),
    db.select().from(sellAssistanceEvents).orderBy(desc(sellAssistanceEvents.createdAt)).limit(1000),
  ]);
  const history = new Map<number, typeof events>(); for (const event of events) history.set(event.requestId, [...(history.get(event.requestId) ?? []), event]);
  return <main className="mx-auto w-full max-w-6xl px-4 py-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-950">Sell My Car Assistance</h1><p className="mt-1 text-sm text-slate-500">Manage customer follow-up without valuations, payment handling or sale guarantees.</p></div><nav className="flex flex-wrap gap-3 text-sm font-semibold text-blue-700"><Link href="/admin/listings">Listings</Link><Link href="/admin/inspections">Inspections</Link><Link href="/admin/users">Users</Link></nav></div>
    {requests.length === 0 ? <p className="mt-6 rounded-xl border border-slate-200 bg-white p-10 text-center text-slate-500">No assistance requests yet.</p> : <ul className="mt-6 space-y-4">{requests.map((request) => { const status = isSellAssistanceStatus(request.status) ? request.status : "requested"; return <li key={request.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-slate-950">SMC-{request.id} · {request.year} {request.makeName} {request.modelName}</h2><span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-900">{sellAssistanceStatusLabel(status)}</span></div><p className="mt-1 text-sm text-slate-700">{request.customerName ?? "Unnamed customer"} · {displayPkPhone(request.contactPhone)}{request.customerEmail ? ` · ${request.customerEmail}` : ""}</p><p className="mt-1 text-sm text-slate-600">{request.mileageKm.toLocaleString("en-PK")} km · {request.vehicleCondition.replaceAll("_", " ")} · {request.ownershipStatus.replaceAll("_", " ")} · registered {request.registrationCity}</p><p className="mt-1 text-sm text-slate-600">{request.address}, {request.cityName} · prefers {request.preferredContact}{request.bestContactTime ? ` · ${request.bestContactTime}` : ""}</p><p className="mt-1 text-sm font-semibold text-slate-800">Seller expectation: {request.expectedPricePkr ? formatPkr(request.expectedPricePkr) : "Not provided"} · timeline: {request.sellingTimeline.replaceAll("_", " ")}</p>{request.sellerNotes && <p className="mt-2 rounded bg-slate-50 p-2 text-sm text-slate-700">{request.sellerNotes}</p>}</div><p className="text-xs text-slate-600">Requested {relativeTime(request.createdAt)}<br />Updated {relativeTime(request.updatedAt)}</p></div><SellAssistanceAdminForm requestId={request.id} status={status} /><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-slate-700">Audit history ({history.get(request.id)?.length ?? 0})</summary><ol className="mt-2 divide-y divide-slate-100 border-l-2 border-slate-200 pl-3">{(history.get(request.id) ?? []).map((event) => <li key={event.id} className="py-2 text-xs text-slate-600"><p><strong>{event.fromStatus ? `${event.fromStatus} → ` : ""}{event.toStatus}</strong> · actor #{event.actorUserId} · {relativeTime(event.createdAt)}</p>{event.customerMessage && <p className="mt-1 text-blue-800">Customer: {event.customerMessage}</p>}{event.internalNote && <p className="mt-1 text-amber-800">Internal: {event.internalNote}</p>}</li>)}</ol></details></li>; })}</ul>}
  </main>;
}
